// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	GetProductById(ctx context.Context, productID uuid.UUID) (Product, error)
	GetProductByName(ctx context.Context, name string) (Product, error)
}

var _ Querier = (*Queries)(nil)
