// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetWalletById(ctx context.Context, walletID uuid.UUID) (GetWalletByIdRow, error)
}

var _ Querier = (*Queries)(nil)
