// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetUserById(ctx context.Context, userID uuid.UUID) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
